### ISSUE TITLE
How to start the Knowledge Graph Studio service from local source code?

### ISSUE THREAD

**Issue by brucewkz** [whyhow-ai/knowledge-graph-studio#16]
## What
_A clear and concise description of what the feature is. Please include any specific functionality and why this feature would be beneficial to the project._

## Why
_Discuss the impact of this feature on current users, system performance, and any other areas of the application. Indicate if this feature would be beneficial to other users._

## Implementation guidance
_Suggest how this feature might be implemented. Include details like API changes, database schema modifications, architectural considerations, and any other relevant implementation details._

**Comment by chiajy2000** [comment]
Hi @brucewkz, we have the instructions in the ReadMe - let us know if there's any steps that are not clear.
