### ISSUE TITLE
Request for Additional Documentation on Auth0 credentials 

### ISSUE THREAD

**Issue by moloodbahar** [whyhow-ai/knowledge-graph-studio#6]
I have noticed that there is no documentation on .env README, specifically for [environment file](https://github.com/whyhow-ai/knowledge-graph-studio/blob/main/.env.sample) # ----------------------- # 
# Auth0
# ----------------------- # 
WHYHOW__API__AUTH0__DOMAIN
WHYHOW__API__AUTH0__AUDIENCE
WHYHOW__API__AUTH0__ALGORITHM 
# ----------------------- # 
Would you please share the necessary environment variables required to set up and use the repo effectively? 
Thank you in advance

**Comment by recchris** [comment]
Hey @moloodbahar, working on adding some more detailed quickstart instructions now. I'll ping you once it is up. Auth0 is the default token-based auth solution we've been using for our UI, but it shouldn't be necessary for running the API server. I will mention this in the docs. Thx!

**Comment by recchris** [comment]
FYI, we just added the following:
- Removed default auth0 logic (not needed for running the knowledge graph studio backend, so this is no longer a dependency for getting started)
- Added scripts for MongoDB Atlas setup, including a cli script for creating all the collections and a script for creating your user (in `src/whyhow_api/cli`)
- Added more detailed instructions to `README` for getting started. We will be continually improving the documentation.

Hopefully that clears it up. Thx!

**Comment by recchris** [comment]
Hey @moloodbahar, closing this issue since the Auth0 piece has been commented out. Thx!
